# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AdminApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


pod 'IQKeyboardManager'
pod 'Firebase'
pod 'Firebase/Auth'
pod 'Firebase/Analytics'
pod 'Firebase/Database'


  # Pods for split-bills

end
